apiVersion: v1
kind: Service
metadata:
  name: awesome-rabbitmq
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 15672
      targetPort: 15672
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: 5672
  selector:
    app: awesome-rabbitmq
